export const GET_ALL_PRODUCTS_START = 'GET_ALL_PRODUCTS_START'
export const GET_ALL_PRODUCTS_COMPLETE = 'GET_ALL_PRODUCTS_COMPLETE'
export const GET_ALL_PRODUCTS_ERROR = 'GET_ALL_PRODUCTS_ERROR'

export const ADD_PRODUCT_START = 'ADD_PRODUCT_START'
export const ADD_PRODUCT_COMPLETE = 'ADD_PRODUCT_COMPLETE'
export const ADD_PRODUCT_ERROR = 'ADD_PRODUCT_ERROR'

export const EDIT_PRODUCT_START = 'EDIT_PRODUCT_START'
export const EDIT_PRODUCT_COMPLETE = 'EDIT_PRODUCT_COMPLETE'
export const EDIT_PRODUCT_ERROR = 'EDIT_PRODUCT_ERROR'

export const DELETE_PRODUCT_START = 'DELETE_PRODUCT_START'
export const DELETE_PRODUCT_COMPLETE = 'DELETE_PRODUCT_COMPLETE'
export const DELETE_PRODUCT_ERROR = 'DELETE_PRODUCT_ERROR'